package com.vedant.querybot.dto;

import java.util.List;
import java.util.Map;

public class NLQueryResponseDTO {
    private String sql;
    private List<Map<String, Object>> rows;
    private String message;
    // Natural language explanation / answer generated by the LLM
    private String nlAnswer;

    public NLQueryResponseDTO() {}

    public NLQueryResponseDTO(String sql, List<Map<String, Object>> rows, String message) {
        this.sql = sql;
        this.rows = rows;
        this.message = message;
    }

    public String getSql() { return sql; }
    public void setSql(String sql) { this.sql = sql; }

    public List<Map<String, Object>> getRows() { return rows; }
    public void setRows(List<Map<String, Object>> rows) { this.rows = rows; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public String getNlAnswer() { return nlAnswer; }
    public void setNlAnswer(String nlAnswer) { this.nlAnswer = nlAnswer; }
}
